name: Deploy TV Backend

on:
  push:
    branches:
      - Serv01

jobs:
  deploy:
    name: Despliegue desde Dockerfile
    runs-on: self-hosted

    steps:
    - name: Clonar repo privado
      run: |
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S rm -rf /tmp/tv-backend
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/moirdaniel/tv-backend.git /tmp/tv-backend

    - name: Liberar completamente el puerto 3000
      run: |
        echo "📦 Contenedores en puerto 3000:"
        sudo docker ps --filter "publish=3000"
        
        echo "🔍 Procesos usando puerto 3000:"
        sudo lsof -i :3000 || true

        echo "🧨 Forzando eliminación de contenedor con puerto 3000 (si existe)..."
        ID=$(sudo docker ps -q --filter publish=3000)

        if [ -n "$ID" ]; then
          echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker kill $ID
          echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker rm $ID
        fi

        echo "🧨 Matando procesos externos en puerto 3000..."
        PORT_PID=$(sudo lsof -ti:3000 || true)
        if [ -n "$PORT_PID" ]; then
          echo "⚠️ Matando proceso externo (PID $PORT_PID)..."
          echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S kill -9 $PORT_PID
          sleep 2
        fi  

    - name: Eliminar contenedor anterior si existe
      run: |
        if [ "$(docker ps -aq -f name=tv-backend)" ]; then
          echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker stop tv-backend || true
          echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker rm tv-backend || true
        fi

    - name: Construir imagen desde Dockerfile
      run: |
        cd /tmp/tv-backend
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker build -t tv-backend:latest .

    - name: Iniciar nuevo contenedor
      run: |
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker run -d \
          --name tv-backend \
          --restart unless-stopped \
          -p 3000:3000 \
          -v /tmp/tv-backend:/app \
          tv-backend:latest

    - name: Verificar contenedor en ejecución
      run: |
        docker ps --filter "name=tv-backend"
