name: Deploy TV Backend

on:
  push:
    branches:
      - Serv01

jobs:
  deploy:
    runs-on: self-hosted
    name: Despliegue desde GitHub privado

    steps:
    - name: Limpiar y clonar desde GitHub
      run: |
        rm -rf /tmp/tv-backend
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/moirdaniel/tv-backend.git /tmp/tv-backend

    - name: Levantar contenedores con Docker Compose
      run: |
        cd /tmp/tv-backend
        docker compose pull
        docker compose up -d --remove-orphans
