name: Deploy TV Backend

on:
  push:
    branches:
      - Serv01

jobs:
  deploy:
    name: Despliegue local en Serv01
    runs-on: self-hosted

    steps:
    - name: Pull últimos cambios
      run: |
        cd /docker-apps/tv-backend
        git pull origin main

    - name: Actualizar contenedores
      run: |
        docker compose pull
        docker compose up -d --remove-orphans

    - name: Verificar estado de servicios
      run: docker ps
