name: Deploy TV Backend

on:
  push:
    branches:
      - Serv01

jobs:
  deploy:
    name: Despliegue usando dmoir
    runs-on: self-hosted

    steps:
    - name: Clonar código desde GitHub privado
      run: |
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S rm -rf /tmp/tv-backend
        git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/moirdaniel/tv-backend.git /tmp/tv-backend

    - name: Copiar archivos al directorio de despliegue
      run: |
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S rm -rf /docker-apps/tv-backend/*
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S cp -r /tmp/tv-backend/* /docker-apps/tv-backend/

    - name: Ejecutar Docker Compose como dmoir
      run: |
        cd /docker-apps/tv-backend
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker-compose pull
        echo "${{ secrets.DMOIR_SUDO_PASSWORD }}" | sudo -S docker-compose up -d --remove-orphans
